#!/bin/bash

# Add here any the actions which are required before plugin build
# like packages building, packages downloading from mirrors and so on.
# The script should return 0 if there were no errors.

set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES_PATH="${ROOT}"/deployment_scripts/puppet/modules
DESIGNATE_PUPPET_MODULE="${MODULES_PATH}/designate"
TMP_DIR="${ROOT}"/tmp
mkdir -p "${DESIGNATE_PUPPET_MODULE}"
mkdir -p "${TMP_DIR}"
PUPPET_DESIGNATE_BRANCH="stable/kilo"
REPO_PATH="https://github.com/openstack/puppet-designate/tarball/${PUPPET_DESIGNATE_BRANCH}"
wget "$REPO_PATH"  -O - | tar xz --strip-components=1 -C "${DESIGNATE_PUPPET_MODULE}"
